# Generated by Django 4.2.6 on 2023-11-11 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracao",
            name="email",
        ),
        migrations.RemoveField(
            model_name="configuracao",
            name="nome_empresa",
        ),
        migrations.RemoveField(
            model_name="configuracao",
            name="slogan",
        ),
        migrations.RemoveField(
            model_name="configuracao",
            name="telefone",
        ),
    ]
