# Generated by Django 4.2.6 on 2023-10-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0002_alter_fornecedor_nome_fornecedor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorie",
            name="produtos",
        ),
        migrations.AddField(
            model_name="itemorder",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="produto.categorie",
            ),
            preserve_default=False,
        ),
    ]
